### ISSUE TITLE
xspec ant task should support filesets/patterns/path elements

### ISSUE THREAD

**Issue by danizen** [xspec/xspec#114]
I've created a `build.xml` that runs xspec tests for each file I list in a directory, but I really want it to run on all files in the directory.

**Comment by cirulls** [comment]
Thanks for your input. I remember having the same issue few years ago when I had to run a bunch of XSpec tests using ant. I give you two ways of doing this:

- [xspec macro](https://github.com/xspec/xspec/wiki/Running-with-Ant#the-xspec-macro): the documentation on the wiki gives you an example on how to run multiple tests within the same ant target. I vaguely recall trying to use this at the time but not succeeding. It would be good if you can give it a go and report if the xspec macro works correctly.
- [for syntax in ant-contrib](http://ant-contrib.sourceforge.net/tasks/tasks/for.html): this is less elegant but it should work. You can see an example in a paper I presented at [XML London 2015](http://xmllondon.com/2015/xmllondon-2015-proceedings.pdf), the example is on page 55. In a nutshell, you install [ant-contrib](http://ant-contrib.sourceforge.net/), use the ```for``` task to iterate over all the XSpec files in a given directory and run a XSpec with Saxon (the example shows an XSL transformation instead but conceptually it is the same). 

I hope this helps, let me know how you're getting on with it.

**Comment by danizen** [comment]
I've used the xspec macro as you describe, and it works.   The issue is that then a developer must add the file both to a tests sub-directory, and also to the ant build.xml.   This is why a fileset is desirable.

It is a modern feature - it used to be that a Junit test suite had to list individual tests, and then, with Java annotations, all you have to list is packages to test.   With a fileset, you can get a similar experience without editing in and out multiple tests.

**Comment by danizen** [comment]
Also, avoiding ant-contrib is the reason I filed this issue :)   ant-contrib is a bit old for me to expect it to work.

**Comment by cirulls** [comment]
Thanks for your input. I agree on ant-contrib, I was never fond of using it and also believe that it should be avoided if possible.

Could you post examples of your ```build.xml``` for ant and XSpec so that I can have a closer look at the code you're referring to? This would allow me to try out few things or to define the specifications for the new feature you're suggesting. Please also let me know which version of ant you're using. Thanks.

**Comment by danizen** [comment]
At this time, the `build.xml` in the master branch of https://github.com/NLM-OCCS/marc2bibframe2/ shows this pattern.   The `tests` sub-directory holds a number of xspec tests.   The `build.xml` pulls down xspec with a `setup` target, and then the `test` target runs the tests.   I haven't written taskdefs for ant since it required Java-code to do it, and so I'm not sure whether it is possible to build a taskdef to accept a fileset without Java...

**Comment by cirulls** [comment]
Thanks for sharing the code, it's always good to have an example. 

To recap so that I understand correctly the specifications for the feature request: at the moment you are running the tests like this in your project:
```xml
<target name="test" description="--> Run xspec tests using Saxon">
    <xspec xspec.xml="test/ConvSpec-001-007.xspec" />
    <xspec xspec.xml="test/ConvSpec-006,008.xspec" />
    ...
</target>
```
This is painful because each time you add a new test you need to list it explicitly in the ant's build file. You want to be able to use a fileset, something like this:
```xml
<fileset dir="${test.dir}" includes="**/*.xspec"/>
```
so that all the XSpec tests in ```test.dir``` are executed. Also, you don't want to use the ant-contrib module.
This work would require to extend the [xspec task in build.xml](https://github.com/xspec/xspec/blob/master/build.xml#L82-L118) so that it can handle these requirements. 

Can you confirm this covers your request so that I can classify this issue as feature request?

**Comment by cirulls** [comment]
By the way, I saw in the [commit history of your project](https://github.com/NLM-OCCS/marc2bibframe2/commit/b894058e23e96579148f7043c14ac54cf67444ae) that you need JUnit output for integration with CI/CD systems. XSpec now supports JUnit by the ```-j``` flag. For an example, see [Integration with Jenkins](https://github.com/xspec/xspec/wiki/Integration-with-Jenkins).

**Comment by AirQuick** [comment]
[`Using Ant to run multiple XSpec tests`](https://github.com/xspec/xspec/wiki/Running-with-Ant#using-ant-to-run-multiple-xspec-tests) in Wiki might help.

**Comment by AirQuick** [comment]
Closing this, as https://github.com/xspec/xspec/issues/114#issuecomment-469007060 doesn't use ant-contrib.
