### ISSUE TITLE
New XSpec release - v0.6.0 or v1.0.0?

### ISSUE THREAD

**Issue by cirulls** [xspec/xspec#139]
## Question
How should the next XSpec release be called? v0.6.0 or v1.0.0? Please add your comments below.

## Background 
Few people asked to release a new version of XSpec so that it can include the latest changes such as the new Schematron support. This will basically be the version that is currently on `master` branch plus some more work that it is still needed on some open issues/pull requests. The new release will be available as a zip file in the [release section](https://github.com/xspec/xspec/releases). As usual, I'd like to follow [semantic versioning](http://semver.org/) as it is a best practice in software releases.   

At the [XML London conference](http://xmllondon.com) I received feedback that the next version of XSpec should be named v1.0.0. Some people feel XSpec is mature enough to move to version 1.x.x and this version number sounds much better than sticking to version 0.x.x for several years. However, I also heard feedback from other people saying that there are some features that are still experimental in the current version so it's better to continue with the next version number, i.e. v0.6.0. 

I don't have a definite opinion myself and I can see the rational behind both opinions. Therefore I would to ask the XSpec community: how do you want the next XSpec release to be called? v0.6.0 or v1.0.0?

**Comment by vincentml** [comment]
That is an interesting question. XSpec is very good, widely used, and has been very stable in the past few years, so it essentially has achieved “1.0.0” status. XSpec also has received a recent wave of new development, including several elements added for Schematron support, that might not be as stable as the rest of XSpec. It might be good to release version 0.6.0 next, see if there is any feedback from users, and then release version 1.0.0. Also, maybe this is just another perception thing, since @cirulls has put new life into XSpec by taking ownership of the project and modernizing the development process it would be really nice to add the “1.0.0” milestone. What should be on the roadmap for version 1.0.0? My suggestions would be:
 
* Improve the HTML report – Related items in GitHub are pull request #138 (which incorporates pull request #111), pull request #71, and issue #92. 
* Improve the Ant build script – Related items in GitHub are issue #80, issue #114, and pull request #138 (which can’t be used directly because it includes changes to the Schematron core XSLTs).

**Comment by cirulls** [comment]
@vincentml, thanks for your comments. I created a [project in GitHub](https://github.com/xspec/xspec/projects/1) where we can prioritize issues and pull requests to be included in the next release of XSpec. I invite everybody in the XSpec community to give comments on which features and bug fixes should be included in the next releases of XSpec. For now, I included @vincentml requests although this may change according to feedback from other people. 

As there are more outstanding issues and pull requests that I can possibly follow, I feel the need to introduce this prioritization mechanism in order to focus on what the XSpec community think is more important to work on. Any pull request that is ready with code review, tests and documentation can obviously be included in the next release but I will tend to focus my efforts towards what the XSpec community feel is more valuable for the development of XSpec.

**Comment by vincentml** [comment]
I mentioned this question during my presentation on XSpec's support for Schematron testing at the [Balisage conference](http://www.balisage.net/) last week and received some comments. Two people commented that XSpec is already stable, so as we are adding new features in the next release the best thing that we can do to increase the adoption of XSpec would be to skip past version 1.0 and go right to version 1.1.

**Comment by AlexJitianu** [comment]
Hi,
I also vote for the 1.0/1.1 for pretty much the same reasons stated above. A 0.6.0 version will still suggest a beta release which could affect user adoption.

**Comment by cirulls** [comment]
XSpec v1.0.0 is now officially released: https://github.com/xspec/xspec/releases/tag/v1.0.0
