### ISSUE TITLE
Cannot compile Schematron tests on Saxon-HE 9.8

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#142]
http://saxonica.com/html/documentation/conformance/xslt30.html
> From 9.8, XSLT 1.0 backwards-compatibility mode requires Saxon-PE or higher (that is, Saxon-HE will reject stylesheets that specify version="1.0").

Because of this limitation, XSpec tests (such as [`run-xspec-tests.sh`](https://github.com/xspec/xspec/blob/master/test/run-xspec-tests.sh) and [`xspec.bats`](https://github.com/xspec/xspec/blob/master/test/xspec.bats)) fail in Schematron on Saxon-HE 9.8.0.4.
> Compiling the Schematron...
> Error on line 146 of iso_dsdl_include.xsl:
>   XTDE0160: XSLT 1.0 compatibility mode is not available in this configuration
> XSLT 1.0 compatibility mode is not available in this configuration
> 
> *** Error compiling the Schematron on step 1

**Comment by vincentml** [comment]
@AirQuick Thanks for flagging this! I'll reach out to @tgraham-antenna regarding updating the Schematron XSLTs. 

A quick search in XSpec source just now did not show any XSLTs that specify version 1.0 apart from the Schematron XSLTs.

**Comment by cirulls** [comment]
@AirQuick: thanks for reporting this. @vincentml: thanks for filing an issue on Schematron GitHub page at https://github.com/Schematron/schematron/issues/55.

@vincentml: I wonder if the work you did in #133 would allow us to use an update version of the Schematron XSLTs. Personally, I would prefer to have Schematron has an external dependency (as we do with Saxon) rather than backing it in the XSpec repository. But other people may have a different opinion...

**Comment by vincentml** [comment]
I would like to keep it so that XSpec works out of the box with only Saxon and Java as dependencies, so I feel reluctant about making the Schematron XSLTs a new external dependency. It seems convenient to allow people to check out the XSpec repository, or download the a release, add Saxon, and start using it. For now I think having a copy of the Schematron XSLTs in the XSpec repository is the best option. 

The use cases that I had in mind for #133 are things that an average user probably would not need to do (which is not to say that other use cases would not be possible). 

1. Help with using XSpec as a framework for testing the Schematron XSLTs
2. Allow testing with other versions of the Schematron XSLTs
3. Allow testing custom Schematron API extensions ([link](http://www.tei-c.org/release/xml/tei/odd/Utilities/schematron-skeleton-api.htm))

I think it would be good to import the Schematron XSLTs from https://github.com/Schematron/schematron into XSpec as a git submodule. However, doing that currently would also import files and cruft that are not needed. The Schematron repository needs to be reorganized. It could be helpful to have a separate repository in the Schematron org that contains only release versions of the Schematron XSLTs to make it easy to import the XSLTs into other projects (including XSpec).

**Comment by tgraham-antenna** [comment]
@vincentml is right on both counts: including Schematron XSLTs as a git submodule would work best (particularly when Schematron gets to the point of tagging stable releases) and the Schematron repository needs to be reorganized.  In the interim, XSpec could include Schematron as a git submodule and extract just the useful parts of Schematron for inclusion in XSpec distributions.

**Comment by cirulls** [comment]
> I think having a copy of the Schematron XSLTs in the XSpec repository is the best option.

I'm happy with that for now, I see your point of not asking users to download another dependency to try out Schematron support in XSpec. 

> I think it would be good to import the Schematron XSLTs from https://github.com/Schematron/schematron into XSpec as a git submodule. 

That would be the best option in the medium term so that we can benefit from upstream changes in the Schematron repository. 

Having said that, I think we cannot use or test XSpec with Saxon 9.8 until Schematron fully moves to XSLT 2.0. It would be good to see a new version of Schematron, I'll be happy to set up Travis for Schematron if this can help the project.

**Comment by tgraham-antenna** [comment]
We're in a chicken-and-egg situation here.  Since Schematron is set to use XSpec for its regression testing, it would help Schematron if there was a stable XSpec release that included the Schematron testing capability.  Could you/I at least tag the current head so that (real soon now) Schematron can pull a known version of the XSpec code for use when testing?

**Comment by cirulls** [comment]
We were planning to release a new version of XSpec soon which officially includes the Schematron support. We wanted to include several other things as well (see https://github.com/xspec/xspec/projects/1) but it's probably better to release the new version soon and then add the rest in another minor release. The ant support in #138 should be ready soon as I'm going to work directly with @markdunnoup in the next days so this will hopefully make it easier to integrate the Schematron support in XSpec. 

@vincentml: as you developed several things that are going to feature in the next release, what's your opinion on this?

**Comment by vincentml** [comment]
A Travis script for Schematron could clone latest code from the XSpec repository for now to get started. Similarly, the Travis script for XSpec uses bats by cloning the bats repository without specifying a specific version. Of course, when the next release of XSpec has been tagged it will be much better for Schematron's Travis script to use a specific tagged version of XSpec.

I'll try to create a pull request for issue #140 in the next few days. This issue includes several useful additions to Schematron support which are already done. The parts that are not yet done can be held for a future release. Just to note, this includes a change to the Schematron XSpec test compilation which should also be incorporated in the ant script.

Pull request #135 is probably ready to be merged unless any feedback comes up in review.

**Comment by cirulls** [comment]
@vincentml: thanks for your feedback. I agree that the Travis script could be used with the latest code on `master` to test Schematron, that would be a good start. Once the next version of XSpec is released, the Travis script could be changed to use that version which is going to be more stable than the `master` branch. As I wrote in https://github.com/Schematron/schematron/issues/49#issuecomment-302860207, if I'm provided with some XSpec tests for testing Schematron (even some trivial ones), I can give a go to implement a continuous integration workflow for the Schematron repository. 

Regarding #135, I'll try to review it next week, please bear with me till then.

**Comment by AirQuick** [comment]
The issue is obsolete (for now).
> * From 9.8.0.7, XSLT 1.0 backwards-compatibility mode is reinstated in Saxon-HE. In earlier versions of 9.8, this mode requires Saxon-PE or higher (that is, Saxon-HE will reject stylesheets that specify version="1.0").

https://www.saxonica.com/html/documentation/conformance/xslt30.html

**Comment by AirQuick** [comment]
Closing this, because
- https://github.com/xspec/xspec/issues/142#issuecomment-353129767
- Schematron/schematron#89
