### ISSUE TITLE
schematron queryBinding="xslt3" not supported?

### ISSUE THREAD

**Issue by joewiz** [xspec/xspec#1461]
Using oXygen 23.1 (on macOS 11.3), when running an XSpec via Apply Transformation Scenario to test a Schematron with the `@queryBinding` set to `xslt3`, I get an error, stating:

> Fail: This implementation of ISO Schematron does not work with schemas using the query language xslt3

Below is the full console output. I've also attached the two files here: [xspec-test.zip](https://github.com/xspec/xspec/files/6400500/xspec-test.zip). The test runs fine if the schematron is set to `@queryBinding="xslt2"`, but it produces this error if set to `xslt3`.

My test doesn't demonstrate use of xslt3 features - just the invocation of `@queryBinding="xslt3"`. (I have Schematron files that use XPath 3.0 and 3.1 features, such as the simple map operator, which aren't available in XSLT 2.0.) 

Is this a limitation of XSpec or is this an issue with the oXygen environment?

```txt
Executing:
"/Applications/Oxygen XML Editor/.install4j/jre.bundle/Contents/Home/jre/bin/java" -Dapple.awt.UIElement=true -Dfile.encoding=UTF-8 -Xmx256m -Djava.awt.headless=true -classpath "/Applications/Oxygen XML Editor/tools/ant/lib/ant-launcher.jar" "-Dant.home=/Applications/Oxygen XML Editor/tools/ant" org.apache.tools.ant.launch.Launcher -lib "/Applications/Oxygen XML Editor/classes" -lib "/Applications/Oxygen XML Editor/lib/oxygenCommons.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygen.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygenDeveloper.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygenEclipse.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygenDeveloperEclipse.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygen-sandbox.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygen-license.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygen-basic-utilities.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygen-editor-variables-parser.jar" -lib "/Applications/Oxygen XML Editor/lib/xml-apis.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygen-patched-resolver.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygen-patched-saxon-9.jar" -lib "/Applications/Oxygen XML Editor/lib/saxon9-sql.jar" -lib "/Applications/Oxygen XML Editor/lib/log4j-1.2-api-2.14.0.jar" -lib "/Applications/Oxygen XML Editor/lib/log4j-core-2.14.0.jar" -lib "/Applications/Oxygen XML Editor/lib/log4j-api-2.14.0.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygen-patched-xerces.jar" -lib "/Applications/Oxygen XML Editor/lib/guava-28.1-jre.jar" -f "build.xml" "-Dcatalog=/Users/joe/workspace/hsg-project/catalog.xml" "-Dclean.output.dir=true" "-Dtest.type=s" "-Dxspec.fail=false" "-Dxspec.project.dir=/Applications/Oxygen XML Editor/frameworks/xspec/" "-Dxspec.result.html=/Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/test-result.html" "-Dxspec.xml=/Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/test.xspec" "-Dwebhelp.trial.license=no"

Buildfile: /Applications/Oxygen XML Editor/frameworks/xspec/build.xml

init:
     [echo] Testing test.xspec [s]
    [mkdir] Created dir: /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/xspec

locate-schematron-file:
     [xslt] Processing /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/test.xspec to /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/xspec/test_xml-to-properties.xml
     [xslt] Loading stylesheet /Applications/Oxygen XML Editor/frameworks/xspec/src/ant/locate-schematron-uri.xsl
     [echo] Path of Schematron file: /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/test.sch

setup-schematron-preprocessor:
     [xslt] Processing /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/test.xspec to /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/xspec/test-sch-step3-wrapper.xsl
     [xslt] Loading stylesheet /Applications/Oxygen XML Editor/frameworks/xspec/src/schematron/generate-step3-wrapper.xsl

preprocess-schematron-xslt:
     [echo] STEP 1: Include modules
     [xslt] Processing /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/test.sch to /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/xspec/test-step1.sch
     [xslt] Loading stylesheet /Applications/Oxygen XML Editor/frameworks/xspec/src/schematron/iso-schematron/iso_dsdl_include.xsl
     [echo] STEP 2: Expand abstracts
     [xslt] Processing /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/xspec/test-step1.sch to /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/xspec/test-step2.sch
     [xslt] Loading stylesheet /Applications/Oxygen XML Editor/frameworks/xspec/src/schematron/iso-schematron/iso_abstract_expand.xsl
     [echo] STEP 3: Convert Schematron to XSLT
     [xslt] Processing /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/xspec/test-step2.sch to /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/xspec/test-sch-preprocessed.xsl
     [xslt] Loading stylesheet /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/xspec/test-sch-step3-wrapper.xsl
     [xslt] Fail: This implementation of ISO Schematron does not work with schemas using the query language xslt3
     [xslt] /Applications/Oxygen XML Editor/frameworks/xspec/src/schematron/iso-schematron/iso_schematron_skeleton_for_saxon.xsl:632:82: Fatal Error! Processing terminated by xsl:message at line 632 in iso_schematron_skeleton_for_saxon.xsl
     [xslt] Failed to process /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/xspec/test-step2.sch

BUILD FAILED
/Applications/Oxygen XML Editor/frameworks/xspec/build.xml:332: The following error occurred while executing this line:
/Applications/Oxygen XML Editor/frameworks/xspec/build.xml:178: Fatal error during transformation using /Users/joe/workspace/hsg-project/repos/frus/schema/xspec-test/xspec/test-sch-step3-wrapper.xsl: Processing terminated by xsl:message at line 632 in iso_schematron_skeleton_for_saxon.xsl; SystemID: file:/Applications/Oxygen%20XML%20Editor/frameworks/xspec/src/schematron/iso-schematron/iso_schematron_skeleton_for_saxon.xsl; Line#: 632; Column#: 82

Total time: 1 second

The process finished with exit code: 1
```

**Comment by AirQuick** [comment]
[The _skeleton_ Schematron implementation](https://github.com/Schematron/schematron) embedded in XSpec does not support `@queryBinding="xslt3`. Unfortunately the implementation has virtually no chance of supporting it, as its development has been halted (Schematron/schematron#89).
Its named successor, [SchXslt](https://github.com/schxslt/schxslt), supports `@queryBinding="xslt3` (schxslt/schxslt#40).

XSpec v2.1 is fully tested with SchXslt v1.7.1. (Earlier versions of SchXslt have some critical [issues](https://github.com/schxslt/schxslt/issues?q=is%3Aissue+author%3AAirQuick+is%3Aclosed).) Unfortunately Oxygen 23.1 comes bundled with XSpec v1.6 which does not work well with the recent versions of SchXslt.

So firstly you have to install XSpec v2.1 instead of the bundled XSpec v1.6. See "[Running the Latest Version of XSpec with Oxygen](https://github.com/xspec/xspec/wiki/Running-with-Oxygen#running-the-latest-version-of-xspec-with-oxygen)" in Wiki.

Secondly you have to set up the Oxygen transformation scenario to use SchXslt v1.7.1 or later. To do so,

1. Download `schxslt-1.7.1-xslt-only.zip` from [SchXslt releases page](https://github.com/schxslt/schxslt/releases) and extract it to somewhere.
1. Make sure you have installed XSpec v2.1 as mentioned previously.
1. Duplicate **Run XSpec Test** transformation scenario.
1. In **Parameters** tab of the duplicated scenario, add these parameters:
   - `xspec.schematron.preprocessor.step1` = `#none`
   - `xspec.schematron.preprocessor.step2` = `#none`
   - `xspec.schematron.preprocessor.step3` = `path/to/schxslt/2.0/pipeline-for-svrl.xsl`
   
   which should look like
   ![schxslt-ant](https://user-images.githubusercontent.com/8489367/116643616-693ce680-a9ac-11eb-8518-54d828bb2dd9.png)

So it's a bit complicated, but it's inevitable as both XSpec and SchXslt are actively developed.

**Comment by joewiz** [comment]
@AirQuick Thank you very much for such a quick, thorough, and empowering reply! This is great news. I will try your steps when get to my first Schematron rules requiring xslt3 bindings. In the meantime, I have a lot of work to do to prepare tests for my plainer Schematron rules. Very excited.
