### ISSUE TITLE
Mention XSpec fiddle

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#1540]
Add https://martin-honnen.github.io/xspec-fiddle/ to Wiki, maybe https://github.com/xspec/xspec/wiki/Related-Projects

**Comment by galtm** [comment]
Hi, @AirQuick and @martin-honnen

I added a listing for XSpec fiddle on the Related Projects page. Feel free to suggest changes in the summary, "a way to run an XSpec XSLT test in a browser." I wrote XSLT because I think it does not support XQuery or Schematron tests, but let me know if that's incorrect.

Neat tool for learning and exploring XSpec! :)
