### ISSUE TITLE
XSpec Users Meetup at XML Prague 2018

### ISSUE THREAD

**Issue by cirulls** [xspec/xspec#158]
I submitted a proposal for an XSpec Users Meetup at XML Prague and it has been [accepted](http://www.xmlprague.cz/2018/01/09/list-of-sessions-for-xml-prague-2018/). The first XSpec Users Meetup will take place on 8th February 2018 between 5.30 and 7pm at the University of Prague in the frame of [XML Prague 2018](http://www.xmlprague.cz).
 
I would like to use this issue to organise the preparatory work for our first XSpec Users Meetup. Together with other XSpec contributors who I know will attend XML Prague I sketched the following programme for the event:

- Overview of XSpec (5 minutes - @cirulls)
- XSpec 101 (10 minutes - @cirulls)
- oXygen plugins (10 minutes - @AlexJitianu)
- New features (e.g. Schematron support) (10 minutes - @cirulls)
- Maven plugin (10 minutes - @cmarchand)
- Use case of integration test with Maven and XSpec  (10 minutes - @mricaud)
- How to contribute to XSpec (5 minutes - @cirulls)
- Q & A

For all the XSpec users who will attend XML Prague 2018: please do join us! We may be able to slot in another 5-10 minute presentation, would you like to propose a topic?

For all those who can't attend XML Prague: we will post updates and materials in this issue to keep you posted, feel free to contribute with ideas and suggestions even if you can't attend in person.

**Comment by cmarchand** [comment]
Advertised here : https://twitter.com/cmarchand7276/status/956272915976282114
Best,
Christophe

January 23, 2018 9:55:53 AM CET Sandro Cirulli <notifications@github.com> wrote:
I submitted a proposal for an XSpec Users Meetup at XML Prague and it has been accepted. The first XSpec Users Meetup will take place on 8th February 2018 between 5 and 6.30pm at the University of Prague in the frame of XML Prague 2018.
I would like to use this issue to organise the preparatory work for our first XSpec Users Meetup. Together with other XSpec contributors who I know will attend XML Prague I sketched the following programme for the event:Overview of XSpec (5 minutes - @cirulls)XSpec 101 (10 minutes - @cirulls)oXygen plugins (10 minutes - @AlexJitianu)New features (e.g. Schematron support) (10 minutes - @cirulls)Maven plugin (10 minutes - @cmarchand)Use case of integration test with Maven and XSpec  (10 minutes - @mricaud)How to contribute to XSpec (5 minutes - @cirulls)Q & A
For all the XSpec users who will attend XML Prague 2018: please do join us! We may be able to slot in another 5-10 minute presentation, would you like to propose a topic?
For all those who can't attend XML Prague: we will post updates and materials in this issue to keep you posted, feel free to contribute with ideas and suggestions even if you can't attend in person.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xspec/xspec","title":"xspec/xspec","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xspec/xspec"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"XSpec Users Meetup at XML Prague 2018 (#158)"}],"action":{"name":"View Issue","url":"https://github.com/xspec/xspec/issues/158"}}}

**Comment by cirulls** [comment]
Thanks @cmarchand for spreading the word!

**Comment by cirulls** [comment]
The XSpec Users Meetup has been moved 30 minutes later, it runs on 8th February 2018 between 5.30 and 7pm, I amended the post.

**Comment by cirulls** [comment]
Here are my [slides for the XSpec Users Meetup](https://github.com/xspec/xspec/files/1703154/xspec-users-meetup.pdf). I will also present Schematron support in XSpec during the Schematron Users Meetup (here are the [slides](https://github.com/xspec/xspec/files/1703155/schematron-users-meetup.pdf)) to spread the word about this new feature within the Schematron community.

**Comment by mricaud** [comment]
Here is my repo for "Use case of integration test with Maven and XSpec": 

https://github.com/mricaud/xml-prague-2018-xspec-integration-testing

You'll find a working example and a few slides.

**Comment by cmarchand** [comment]
My slides of Using Maven to unit test with XSpec :
[unit-tests-with-maven.pdf](https://github.com/xspec/xspec/files/1710150/unit-tests-with-maven.pdf)

**Comment by cirulls** [comment]
Closing this issue as the presentations have been uploaded and linked [here](https://github.com/xspec/xspec/wiki/Presentations-and-demos-on-XSpec).
