### ISSUE TITLE
support for xml catalogs

### ISSUE THREAD

**Issue by sbulka** [xspec/xspec#167]
My templates rely on one main catalog for resolving local stylesheet locations.
I thus need to use this catalog with xspec.sh.

Changes needed:

- CLI option ```--catalog``` (passed to saxon)
- add the Apache catalog resolver library to classpath (needed by saxon to support individual catalogs)

Question:
- Should it be up to the user to provide the catalog resolver on classpath, or should it be added to the project?
Having to do more setup, extra downloads etc. is not encouraging for new users.

**Comment by vincentml** [comment]
Catalog resolver support would be helpful! I have an idea of how to create unit tests for catalog support. I'll send a pull request to add this feature soon.

**Comment by sbulka** [comment]
For testing I would use some dummy catalog and xpath doc-available#1
Obviously need to add xml-resolver.jar to the repo then?

If you want to take a look, I added the option on my fork in this commit:
https://github.com/sbulka/xspec/commit/c735e1354cbd233bfea4ec3f0311848a1c73a8c5

Just trying to get a few test cases running with our templates.
Want to show working xspec to my team this week.

**Comment by vincentml** [comment]
The feature to be able to use XML Catalogs with `xspec.bat/sh` has been added on branch `test/167`. Here is a short guide on how to use this feature which might be useful for testing and eventually for documentation in the wiki.

In order to use XML Catalogs with xspec.bat or xspec.sh an XML Catalog Resolver must be included in the Java classpath. The XML Catalog Resolver from Apache is available at https://mvnrepository.com/artifact/xml-resolver/xml-resolver/1.2. 

If you have installed XSpec by setting the SAXON_HOME environment variable, the resolver jar should be named `xml-resolver-1.2.jar` and placed in the same folder as the Saxon jar. 

If you have installed XSpec by setting the SAXON_CP environment variable, SAXON_CP should be updated to include the location of the resolver jar. For example,

On Windows:

`set SAXON_CP=C:\Programs\xspec\saxon\saxon9he.jar;C:\Programs\xspec\saxon\xml-resolver-1.2.jar`

On Max/Linux:

`export SAXON_CP=~/saxon/saxon9he.jar:~/saxon/xml-resolver-1.2.jar`


The folder `test/catalog` contains files for testing catalog support.

The new command line parameter `-catalog` can be used to specify the location of an XML Catalog file. For example,

On Windows:

`bin\xspec.bat -catalog:test\catalog\catalog-01-catalog.xml test\catalog\catalog-01-xslt.xspec`

On Max/Linux:

`bin/xspec.sh -catalog:test/catalog/catalog-01-catalog.xml test/catalog/catalog-01-xslt.xspec`

**Comment by AirQuick** [comment]
> `bin\xspec.bat -catalog:test\catalog\catalog-01-catalog.xml test\catalog\catalog-01-xslt.xspec`

I usually find it difficult to work with this kind of parameter convention. If you type up to `bin\xspec.bat -catalog:t[cursor here]` on command prompt and hit Tab key, auto-complete does not work, whereas typing `bin\xspec.bat -catalog t[cursor here]` and hitting Tab just works.

**Comment by vincentml** [comment]
Thanks for the suggestion @AirQuick . I had used the `-catalog:` syntax because this syntax is used by Saxon, and it seemed easier to parse. I've changed the syntax to use a space instead of a colon. While doing so I also added a new environment variable XML_CATALOG to provide an alternative way to specify an XML Catalog file. I've edited my comment above to reflect these changes.

**Comment by AirQuick** [comment]
Catalog support is in [v1.1.0](https://github.com/xspec/xspec/releases/tag/v1.1.0)+
