### ISSUE TITLE
Modified expect with \n..

### ISSUE THREAD

**Issue by o-sapov** [xspec/xspec#1700]
The expected result is changed by adding new lines and dots and fails 

![grafik](https://user-images.githubusercontent.com/24490898/226647158-ae4d4661-44f7-43a1-ade9-30f15faed58c.png)

if it is referenced:
<details>
<summary>Click to see XSpec</summary>
<p>

```xml
  <x:scenario focus="on" label="match choice">
    <x:context href="input/input_1.xml" select="/"/>
    <x:expect href="output/output_1.xml" label="choice replaced by type." select="/"/>  
  </x:scenario>
```
</p>
</details> 

But there are no problems when a literal expected result:

<details>
<summary>Click to see XSpec</summary>
<p>

```xml

<x:scenario focus="on" label="match choice">   
    <x:context href="input/input_1.xml" select="/"/>
    <x:expect label="choice replaced by type."><mei meiversion="4.0.1" xmlns="http://www.music-encoding.org/ns/mei">
        <trill accidupper="s" place="above" staff="1" startid="#note_7428" type="accidupper_supplied_NMA-editors" xml:id="trill_7614"/>
      </mei>
    </x:expect>
  </x:scenario>
```
</p>
</details> 

I'm using oXygen v25, and XSPec Framework 2.2.6

The full example you may try here:

[supply_trill_accidupper-lower.zip](https://github.com/xspec/xspec/files/11029702/supply_trill_accidupper-lower.zip)

Possibly relates to https://github.com/xspec/xspec/issues/1155

**Comment by AirQuick** [comment]
`output_1.xml` is indented. In other words, it has whitespace-only text nodes between elements.
Since `x:expect/@href` keeps whitespace-only text nodes intact, your expected result has whitespace-only text nodes as they are in `output_1.xml`. In the expected result (right side) in your screenshot, `\n` and `.` represent those whitespace-only text nodes. (See [Wiki](https://github.com/xspec/xspec/wiki/Understanding-Test-Results#whitespace-only-text-node) for what `\t` `\n` `\r` characters mean.)

I haven't looked into your stylesheet, but I guess it's implicitly or explicitly discarding whitespace-only text nodes inside `<mei>` or around `<trill>`. The actual result (left side) in your screenshot has no whitespace-only text nodes represented by `\n` or `.`.

When XSpec compares the actual result and the expected result, all nodes are considered as significant. Whitespace-only text nodes are not ignored. Your actual result has no whitespace-only text nodes, but your expected result has some. XSpec compared them, found them different and declared Failure.

On the other hand, `x:expect[empty(@href)]` discards whitespace-only text nodes. That's why you found "no problems when a literal expected result". Your expected result has no whitespace-only text nodes.

For more details about whitespace-only text nodes, see [Wiki](https://github.com/xspec/xspec/wiki/Whitespace-only-Text-Nodes).

**Comment by o-sapov** [comment]
Thank you for quick response and a very good explanation. There should be an issue with whitespace. Nevertheless, I'm still getting a wrong test result.

![grafik](https://user-images.githubusercontent.com/24490898/226871260-fa15194f-520c-460e-a156-eff5b9dff342.png)

The expected result gets a line break.
![grafik](https://user-images.githubusercontent.com/24490898/226871448-e77ff84d-105e-4124-b2b6-97f38f65ea80.png)

Otherwise the files are identical when applying the diff:

![grafik](https://user-images.githubusercontent.com/24490898/226873313-625f5dc6-8692-409a-9cf6-49317b084720.png)

(I also removed the XML declaration as I thought, this might be a problem).


 I just used the `test-helper.xsl` you've provided and configured my xspec as in the tutorial:

<details>
<summary>Click to see XSpec.</summary>
<p>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<x:description run-as="external" stylesheet="../supply_trill_accidupper-lower.xsl" xmlns:test-helper="x-urn:tutorial:helper:ws-only-text:test-helper" xmlns:mei="http://www.music-encoding.org/ns/mei" xmlns:x="http://www.jenitennison.com/xslt/xspec">


  <x:helper stylesheet="../../lib/test-helper.xsl"/>

  <x:scenario label="match choice">
    <!--    <x:param href="input/input_1.xml" name="global-context-item"/>-->
    <x:context href="input/input_1.xml" select="/"/>
    <!--    <x:expect href="output/output_1.xml" label="choice replaced by type."  select="/"/>-->
    <x:expect label="choice replaced by type."><mei meiversion="4.0.1" xmlns="http://www.music-encoding.org/ns/mei">
        <trill accidupper="s" place="above" staff="1" startid="#note_7428" type="accidupper_supplied_NMA-editors" xml:id="trill_7614"/>
      </mei>
    </x:expect>
  </x:scenario>

  <x:scenario label="choice with no supplied">
    <!--    <x:param href="input/input_1.xml" name="global-context-item"/>-->
    <x:context href="input/input_2.xml" select="test-helper:remove-whitespace-only-text(.)"/>
    <x:expect href="output/output_2.xml" label="choice replaced by type."  select="test-helper:remove-whitespace-only-text(.)"/>
    <!--<x:expect label="choice replaced by type."><mei meiversion="4.0.1" xmlns="http://www.music-encoding.org/ns/mei">
        <choice xml:id="choice_10188">
          <corr resp="#NMA-editors" xml:id="corr_10188">
            <trill extender="true" lform="wavy" place="above" staff="4" startid="#note_10137" tstamp2="2.7" xml:id="trill_10188a"/>
          </corr>
          <orig xml:id="orig_10188">
            <trill extender="false" place="above" staff="4" startid="#note_10137" xml:id="trill_10188b"/>
          </orig>
        </choice>
      </mei>
    </x:expect>-->
  </x:scenario>

</x:description>

```
</p>
</details>



Possibly, the difference is in the XSL?



<details>
<summary>Click to see XSL (though without dependencies).</summary>
<p>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<stylesheet exclude-result-prefixes="xs mei xd dme functx" version="3.0" xmlns="http://www.w3.org/1999/XSL/Transform" xmlns:dme="http://www.mozarteum.at/ns/dme" xmlns:functx="http://www.functx.com" xmlns:map="http://www.w3.org/2005/xpath-functions/map" xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:mei="http://www.music-encoding.org/ns/mei" xpath-default-namespace="http://www.music-encoding.org/ns/mei">


  <xi:include href="docs.xsl" xpointer="element(/1/1)"/>
  <include href="../lib/basic.xsl"/>
  <include href="../lib/functions/functx-1.0-doc-2007-01.xsl"/>
  <include href="../lib/functions/functions_DIME.xsl"/>
  <include href="../lib/applicationChanges.xsl"/>



  <template match="/">
    <variable name="process.choice">
      <apply-templates select="." mode="process.choice"/>
    </variable>

    <sequence>
      <apply-templates mode="applicationChanges" select="$process.choice"/>
    </sequence>
  </template>


  <xd:doc>
    <xd:desc>
      <xd:p>Matches choice with trill that have supplied @accidupper or @accidlower</xd:p>
    </xd:desc>
  </xd:doc>
  <template mode="process.choice" match="choice[corr[supplied[trill]] and orig[trill]]">
    <choose>
      <when test="corr/supplied/trill[@accidupper] and orig/trill[not(@accidupper)]">
        <call-template name="create.trill">
          <with-param name="trill" select="corr/supplied/trill[@accidupper]"/>
          <with-param name="supplied.attribute.name" select="corr/supplied/trill/@accidupper/name()"/>
        </call-template>
      </when>
      <when test="corr/supplied/trill[@accidlower] and orig/trill[not(@accidlower)]">
        <call-template name="create.trill">
          <with-param name="trill" select="corr/supplied/trill[@accidlower]"/>
          <with-param name="supplied.attribute.name" select="corr/supplied/trill/@accidlower/name()"/>
        </call-template>
      </when>
      <otherwise>
        <call-template name="copy.element"/>
      </otherwise>
    </choose>
  </template>



  <xd:doc>
    <xd:desc>Copies the tril from corr with all its attributes. Adds @type.</xd:desc>
    <xd:param name="trill"/>
    <xd:param name="supplied.attribute.name"/>
  </xd:doc>
  <template name="create.trill">
    <param name="trill" as="element()"/>
    <param name="supplied.attribute.name" as="xs:string"/>


    <variable name="type.value">
      <variable name="resp.value" select="$trill/parent::supplied/@resp => substring-after('#')"/>
      <value-of select="$supplied.attribute.name || '_' || 'supplied_' || $resp.value"/>
    </variable>

    <copy-of select="
        dme:add-mei-attributes(
        $trill, xs:QName('type'), $type.value)"/>
  </template>


  <variable name="currentStylesheet" select="doc('')"/>
</stylesheet>


</x:description>
```
</p>
</details

**Comment by AirQuick** [comment]
Looks like your actual result is an *element* node (`element(mei)`) while your expected result of `x:expect[@href]` is a *document* node (`document-node(element(mei))`). Since an *element* node and a _document_ node are different node types (even if the document node contains the same element), the test result is Failure.

If you run XSpec without using Oxygen's **XSpec Helper View** add-on, then you should get a test report like https://github.com/xspec/xspec/wiki/images/xpath-from.png where the difference is highlighted in `XPath ... from` colored in pink. For more details, see the **Difference in XPath ... from** section in [Wiki](https://github.com/xspec/xspec/wiki/Understanding-Test-Results#difference-in-xpath--from). Unfortunately Oxygen's **XSpec Helper View** add-on removes this critical info from its **Q-Diff**...

Probably what you want to write is something like this:

```xml
<x:expect
   href="output/output_2.xml"
   label="choice replaced by type."
   select="test-helper:remove-whitespace-only-text(.)/mei" />
```

Note `/mei` in `@select`. See [Wiki](https://github.com/xspec/xspec/wiki/Selecting-Nodes) for how `x:context`, `x:expect`, `x:param` and `x:variable` work with or without `@select` and `@href`.

**Comment by o-sapov** [comment]
Thank you very much for a very good explanation!

**Comment by AirQuick** [comment]
> Unfortunately Oxygen's **XSpec Helper View** add-on removes this critical info from its **Q-Diff**...

Opened xspec/oXygen-XML-editor-xspec-support#50 .
