### ISSUE TITLE
Question: using a backslash in xspec

### ISSUE THREAD

**Issue by jbriner-pearson** [xspec/xspec#1926]
I have a scenario that contains this:

```xslt
<x:call template="cxml">
                    <x:param name="content">
                        <qti-assessment-item>
                            <qti-item-body>
                                <div class="qti-layout-row"><div class="qti-layout-col6 qti-layout-offset3"><qti-choice-interaction>
                                    <qti-prompt>
                                        <x:text>dilation </x:text><qti-math data-latex="J^{\prime}"></qti-math>
                                    </qti-prompt>
                                    <qti-simple-choice identifier="A">Choice A</qti-simple-choice>
                                </qti-choice-interaction>
                                </div></div>
                            </qti-item-body>
                        </qti-assessment-item>
                    </x:param>
                </x:call>
``` 
The issue is the backslash on  \prime. I cannot get that into the input. It works fine when the xslt transform (Saxon) is running. However, when I run xspec, I get errors. I have tried & #x5C; and \\\\, also without luck.  Suggestions? I have a lot more of these to add. However, if I can get this to work, I am sure that I can get the others.

TIA

**Comment by galtm** [comment]
Hi,

The short answer is to double the curly braces in your content's attribute values (like `data-latex="J^{{\prime}}"`) when the expression inside the braces isn't meant to be XPath.

Longer answer:

XSpec thinks the attribute `data-latex="J^{\prime}"` in your provided parameter value is an attribute value template and sets things up so that Saxon will evaluate the part inside the curly braces as an XPath expression. The error occurs because `\prime` is not a valid XPath expression. In your case, I'm inferring that your intention is for the attribute value to store LaTeX, _not_ text with an embedded XPath expression. Doubling the curly braces tells the XSLT processor to replace `{{` with `{`, replace `}}` with `}`, and not evaluate the text inside the braces. XSpec won't double the curly braces internally on your behalf, because it doesn't know if you want the expression inside to be evaluated or taken literally.

As for why the attribute doesn't cause a problem when you run your XSLT transformation in Saxon, your XSLT probably has nothing in it that interprets the value of `data-latex` as an attribute value template, so the misinterpretation just doesn't arise.

I hope this helps!

**Comment by jbriner-pearson** [comment]
Thank you for your explanation. It was very helpful.

**Comment by galtm** [comment]
Happy to help. I'll mark this issue complete.

**Comment by galtm** [comment]
@jbriner-pearson , I should have also mentioned that an alternative solution is to make XSpec load the XML content from an external XML file by using the `href` attribute (and `select` as well, if you want to select a portion of a document) in `<x:context>`. The XPath evaluation behavior I described earlier happens only when the XML content is embedded directly in the XSpec file.
