### ISSUE TITLE
xsl:for-each Code Coverage Non-Conformance

### ISSUE THREAD

**Issue by birdya22** [xspec/xspec#1949]
### Current Non-Conformance
The `xslt-code-coverage-behavior-by-element.md` file says that `xsl:for-each` elements should be marked based on the XSpec trace data.
The `coverage-report.xsl` in 3.0.3 marks them correctly but uses trace data from their child elements rather than trace data from the `xsl:for-each` element itself.

### Changes in `coverage-report.xsl`
The `coverage-report.xsl` in 3.0.3 includes `xsl:for-each` as a match in a `xsl:template` that has the following comment above it:
``
The rule needs to be amended to use the XSpec trace data for the `xsl:for-each` element.

### Changes in `test/end-to-end/cases-coverage/expected`
None.

**Comment by galtm** [comment]
Now that the `end-to-end/cases-coverage/xsl-map-01.xsl` file has an instance of `xsl:for-each` whose only child is `xsl:map-entry` (which is never traced), that coverage report currently has a bug where `xsl:for-each` is marked as "missed" instead of "hit". So, I added the "bug" label, and we can expect the fix for this issue to change that particular coverage report.
