### ISSUE TITLE
Embedded XML in x:context as a document-node()

### ISSUE THREAD

**Issue by birdya22** [xspec/xspec#2020]
I've struggled to create a test with a Matching Scenario using embedded XML which will match a template with `match="/"`. It works fine using `@href` rather than embedded XML.

I worked out that the embedded XML produces a `node()` whereas the `@href` produces a `document-node()`.
My solution was to add `select="/"` on the `x:context` element containing my embedded XML and that fixed my issue.

Is this the best way of achieving this, and would it be worth adding something to the Wiki about this.

Adrian

**Comment by galtm** [comment]
Hi, Adrian. Yes, adding `select="/"` on the `x:context` element is the best way of achieving this with embedded XML. The wiki describes the current behavior on the [Selecting Nodes](https://github.com/xspec/xspec/wiki/Selecting-Nodes) page. However, selecting nodes wasn't really the task you were trying to accomplish, so that page might not appear to be relevant.

What do you think about my updating the [Indicating the context to match](https://github.com/xspec/xspec/wiki/Writing-Scenarios#indicating-the-context-to-match) section to refer to the Selecting Nodes page? Maybe after the "A big difference between the methods..." paragraph, we can have something like "An additional difference is in the data type produced when `x:context` has no `select` attribute; see Selecting Nodes for details." I'll also think about whether the discussions of parameters and XSpec variables can use a small enhancement.

**Comment by birdya22** [comment]
You are correct in that I wasn't thinking about selecting nodes and so didn't check that page out.

You suggestion looks good to me. 

Adrian

**Comment by galtm** [comment]
Thanks for your input/review. I made three small updates on the Writing Scenarios page ([diffs](https://github.com/xspec/xspec/wiki/Writing-Scenarios/_compare/c806fcf1f5b5dd6bb0b3d6b2b16cbb60d25aaaab...9a2914dac7f185805cfd7ca5b9d27983f4749088)), in these areas:

- Subsection about context, as discussed above
- "XSpec Variables" subsection
- "Describing only the expected result" subsection

I didn't change any content about parameters. Currently, the discussion of function parameters refers to the discussion of contexts; the discussion of named template scenarios refers to the discussion of function scenarios; and the discussion of global parameters refers to the discussions of parameters for named templates and functions.

**Comment by galtm** [comment]
FYI, I suspect that other XSpec users might have questions similar to yours, and this issue inspired me to [write an external topic](https://medium.com/@xspectacles/element-or-document-node-610bba3114e4) about the element vs. document node distinction as it pertains to XSpec.
