### ISSUE TITLE
@test for context on expect not working as expected

### ISSUE THREAD

**Issue by yamahito** [xspec/xspec#26]
Tests which work perfectly well under Oxygen aren't working with the latest release (running using ANT); it looks like it's a problem with impl:context-tmp not evaluating properly.  I'd take a look, but I'm not quite sure what the intention is here - can someone shed any light?

example xspec:

```xml
<x:description xmlns:x="http://www.jenitennison.com/xslt/xspec" stylesheet="test.xsl">

  <x:scenario label="When converting Units">
      <x:context>
         <document>
          <heading>Some Text</heading>
         </document>
      </x:context>
      <x:expect label="Create an container">
         <container>...</container>
      </x:expect>
      <x:expect label="...With a child" test="container/child[1]">
         <child>Some Text</child>
      </x:expect>
   </x:scenario>

</x:description>
```

And some XSLT:

```xml
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  exclude-result-prefixes="xs"
  version="2.0">
  
  <xsl:template match="document">
    <container>
      <xsl:apply-templates/>
    </container>
  </xsl:template>
  
  <xsl:template match="heading">
    <child>
      <xsl:apply-templates/>
    </child>
  </xsl:template>
  
</xsl:stylesheet>
```

**Comment by cirulls** [comment]
Hi @yamahito!

thanks for the question. I think I need some more information from you. I am able to run the above snippets of code using the shell script as follows (I used 26.xspec as filename):
```bash
$ bin/xspec.sh tutorial/26.xspec 
Saxon script not found, invoking JVM directly instead.

Creating Test Stylesheet...

Running Tests...
Testing with SAXON HE 9.7.0.7
When converting Units
Create an container
...With a child
      FAILED

Formatting Report...
passed: 1 / pending: 0 / failed: 1 / total: 2
Report available at tutorial/xspec/26-result.html
Done.
```
This generates the following results:
![26](https://cloud.githubusercontent.com/assets/13256236/21090237/2c19e4f6-c036-11e6-91e7-eb4c0ff0ccfc.png)
Could you post what your current and expected results are? If you're running it with ant, could you specify which version of ant you're using so that I can replicate it?

Thanks,

Sandro

**Comment by yamahito** [comment]
Hi Sandro

I get the same result you do when I run with ANT: However, I don't think
that there should be any failures!

T

**Comment by cirulls** [comment]
There are differences between the file [generate-xspec-tests.xsl](https://github.com/xspec/xspec/blob/master/src/compiler/generate-xspec-tests.xsl) in the xspec repository and in Oxygen (I'm using Oxygen 14.2 as a reference). 

The issue seems to be in the template which is suspiciously called ```x:output-expect-FIXME-TOREMOVE```. If you rename this template as ```x:output-expect``` and remove [this template with the same name](https://github.com/xspec/xspec/blob/master/src/compiler/generate-xspec-tests.xsl#L511-L752) you get the results you expect (i.e. no failing tests). There is also [another difference in $imp:context](https://github.com/xspec/xspec/blob/master/src/compiler/generate-xspec-tests.xsl#L211), the Oxygen file reads ```<for-each select="$context">```, but this doesn't seem to create any difference in the final output in this specific case.

I remember this issue being mentioned by @cmarchand in https://github.com/expath/xspec/pull/74. I have not yet assessed the impact of removing that chunk of code and I definitely want to run the test suite to check that it is not breaking anything but I may have time only towards the end of the week. In the meantime, could you check if it works at your end with the change explained above?

Thanks,

Sandro

**Comment by yamahito** [comment]
I can confirm that the tests appear to run correctly if I swap the names of `x:output-expect-FIXME-TOREMOVE` and `x:output-expect`.

If I get some time I'll try to have a look at the tests myself (no promises)!

**Comment by AirQuick** [comment]
Maybe related in part? https://github.com/expath/xspec/issues/46

**Comment by cirulls** [comment]
@yamahito : I merged #38 into branch master, this should fix your issue. Can you confirm it is fine at your end?

**Comment by fgeorges** [comment]
No, the result of applying templates to the element `document` is the element `container`.  So the following must fail (as it tries to get the child `child` of the child `container` of the result which is the `container` element itself):

```xml
<x:expect label="...With a child" test="container/child[1]">
   <child>Some Text</child>
</x:expect>
```

The correct test is the following (gets the child `child` of the result element, that is, `container`):

```xml
<x:expect label="...With a child" test="child[1]">
   <child>Some Text</child>
</x:expect>
```

**Comment by AirQuick** [comment]
But, if the result is a sequence of nodes, it is wrapped in a document node and this document is set as the context node of the expression, wasn't it?

**Comment by fgeorges** [comment]
Only if there are more than 1 node.  This I think is an unfortunate legacy, as it is not possible to test precisely the result of a template or function returning more than 1 node (it is only possible to test the resulting node of copying the result sequence to a new document node).  This is by the way part of what `@assert` and `@context` try to address: being able to write expressions against the actual result.

I am fixing `master` now.  I am going to keep the behaviour to get a document node even if there is only 1 node, but I think we should consider it otherwise.  This requires as well to wrap the expected result in a document node as well.

**Comment by fgeorges** [comment]
Actually, the document node wrapping was not on the result itself, but on the rsult of applying the `@test` expression when there was one, before comparing it to `expect/@href`, `expect/@select` or `expect/node()`.

**Comment by cirulls** [comment]
> I am fixing ```master``` now.

@fgeorges : please do not push changes directly into ```master```. As I wrote in https://github.com/xspec/xspec/issues/97#issuecomment-284841929, you need to raise a pull request with your changes so that it can be reviewed. A pull request automatically triggers the [Travis](https://travis-ci.org/xspec/xspec) and [AppVeyor](https://ci.appveyor.com/project/xspec/xspec) continuous integration servers. Tests are currently red and we need to fix this first otherwise we can't understand which change broke what.

**Comment by fgeorges** [comment]
Of course.  Pushing to master was a mistake (I did create a branch, just failed to see there was an error, so I was on master that whole time).  Sorry about that.  What I meant above is that I am working on getting master green again, by working on a fix branch.

**Comment by cirulls** [comment]
Sorry @fgeorges, I misunderstood your previous comment. That's perfectly fine, I look forward to getting the fix branch, thanks.
