### ISSUE TITLE
Pending label containing curly bracket crashes

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#447]
```xml
	<x:pending>
		<x:label>{</x:label>
		<x:scenario label="scenario" />
	</x:pending>
```

or

```xml
	<x:pending label="{">
		<x:scenario label="scenario" />
	</x:pending>
```

or

```xml
<x:scenario label="scenario" pending="{"/>
```

crashes both on XSLT and XQuery

**Comment by galtm** [comment]
@AirQuick: I see that you logged several issues related to curly brackets. I found an issue where the compiled test is invalid if `//x:context/x:param/@select` uses syntax like `select="map{'key': 'myvalue'}"`. Should I log a new issue, or does what I described sound redundant with what's already fixed in #463?

**Comment by AirQuick** [comment]
@galtm 
Can you log a new issue?
I didn't know the problem you found. If it's already fixed, it's just an incidental result of a certain fix.

**Comment by galtm** [comment]
@AirQuick
Here is the new issue: https://github.com/xspec/xspec/issues/538
