### ISSUE TITLE
test/*.xspec refers to schema in googlecode

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#56]
These URLs in test/*.xspec files are obsolete. So they can't be validated without catalog.
 ```
generate-tests-utils.xspec(9): <?oxygen RNGSchema="http://xspec.googlecode.com/svn/trunk/xspec.rnc" type="compact"?>
xspec-focus-2.xspec(9): <?oxygen RNGSchema="http://xspec.googlecode.com/svn/trunk/xspec.rnc" type="compact"?>
xspec-function.xspec(9): <?oxygen RNGSchema="http://xspec.googlecode.com/svn/trunk/xspec.rnc" type="compact"?>
xspec-import.xspec(9): <?oxygen RNGSchema="http://xspec.googlecode.com/svn/trunk/xspec.rnc" type="compact"?>
xspec-imported.xspec(9): <?oxygen RNGSchema="http://xspec.googlecode.com/svn/trunk/xspec.rnc" type="compact"?>
xspec-pending.xspec(9): <?oxygen RNGSchema="http://xspec.googlecode.com/svn/trunk/xspec.rnc" type="compact"?>
xspec-rule.xspec(9): <?oxygen RNGSchema="http://xspec.googlecode.com/svn/trunk/xspec.rnc" type="compact"?>
xspec-variable.xspec(9): <?oxygen RNGSchema="http://xspec.googlecode.com/svn/trunk/xspec.rnc" type="compact"?>
```
Maybe they should be updated using a relative path? (`../src/schemas/xspec.rnc`)

**Comment by cirulls** [comment]
Thanks for spotting it. This should be fixed for release v0.5.0. 

We can either use a relative path: `../src/schemas/xspec.rnc`
Or a URL: https://github.com/xspec/xspec/blob/master/src/schemas/xspec.rnc

In general, I favour absolute paths and URLs but in this case it will tie it to the master branch and it will problematic on other branches. 

What do you think it's better?

**Comment by AirQuick** [comment]
Another option would be just removing the `<?oxygen RNGSchema=...` processing instructions.
Probably the PI line was useful circa 2010, but today Oxygen (with its built-in XSpec) validates *.xspec files without it.

**Comment by cirulls** [comment]
@AirQuick : I removed the `<?oxygen RNGSchema=...` processing instructions as you recommended. I also removed obsolete references to `xspec.google.com` into comments. I checked that no obsolete references are present any more with this command under Linux:
```
$ grep -R "googlecode" .
```
I erroneously committed the code straight into `master` instead of raising a pull request, my bad. Since these are just cosmetic changes, could you check that you agree with them? If not, I'm happy to revert to the previous version and do it properly. The diff with the previous version is at a6bb23507e11277d07b06914fc9a5590401e22f7 Note that my editor settings have a different formatting, hence the removal of whitespace in some files (no code has changed, just processing instructions or comments).

**Comment by AirQuick** [comment]
Verified the changes ignoring whitespaces. Thanks.

**Comment by cirulls** [comment]
I found other old references to google repositories so I fix it.

**Comment by AirQuick** [comment]
Looks good too.
