### ISSUE TITLE
Priority of focus and pending

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#575]
How focus and pending work together is not well defined. See https://github.com/xspec/xspec/issues/528#issuecomment-493077875.

We would need to
- [x] Test the behavior, whatever the current behavior is
- [x] Define the expected behavior
- [x] Fix the behavior (if necessary)
- [x] Consider creating Schematron rules for detecting meaningless `x:pending`, `@pending` or `@focus`
- [x] Update Wiki

**Comment by galtm** [comment]
Re #711 , in `//x:scenario[@expand-text="yes"][@pending]/x:scenario[@focus]`, should `@expand-text` take effect if not overridden? Answering that could be part of addressing this issue.

**Comment by AirQuick** [comment]
If we make any changes, we may want to consider accumulator: https://github.com/xspec/xspec/pull/1225#issuecomment-696858512

**Comment by galtm** [comment]
Another related comment: https://github.com/xspec/xspec/pull/1415#discussion_r602930299

In general, my current leaning is that in case `focus` and `pending` occur at different hierarchy levels, we should honor the nearest ancestor-of-self instruction but also process inheritances as needed.

**Comment by AirQuick** [comment]
Reconsider `@focus` in relation to not only `x:pending//x:expect` but also `x:expect/@pending`: https://github.com/xspec/xspec/pull/1412#discussion_r606810062

**Comment by galtm** [comment]
I'd like to defer this item from v2.3 to v2.4 so we can release v2.3 soon. XSpec hasn't had a release in a long time, and I'm not aware that anyone is actively working on this item at the moment. @AirQuick , if you are, in fact, working on this and want it to be in v2.3, please let me know.

**Comment by galtm** [comment]
> If we make any changes, we may want to consider accumulator: [#1225 (comment)](https://github.com/xspec/xspec/pull/1225#issuecomment-696858512)

The code was already improved significantly in #1420, and #1734 proposes using an accumulator to simplify one piece of the current code in this area.

**Comment by galtm** [comment]
I thought about this to see if I had any strong opinions with rationales. I'm on the fence about keeping the current behavior or changing it. Maybe a change is not worth the trouble due to the lack of an obvious winning design and low frequency of situations that would benefit from a change.

Here are some notes in case that helps anyone else reach or articulate an opinion.

## Current execution behavior

Focus takes precedence over pending. For instance:

* When a focused scenario is a descendant of `x:pending` or a pending scenario, focus wins.

* When a focused scenario contains an element with `@pending` or an `x:pending` element, focus wins.

* When an element has both `@focus` and `@pending`, focus wins.

Earlier comments discuss whether to implement a different behavior, where the nearest ancestor-or-self wins. That would change the 2nd case above. The 3rd case above could change or stay the same.

## Workflows and markup life span
I feel that focus and pending aren't simply logical opposites, but rather they play different roles in a workflow.

I use `@focus` for short-term development convenience. I wouldn't want a file with `@focus` to go beyond my local work area or local commits (not counting tests for `@focus` in this repo itself, of course).

I use `@pending` or `<x:pending>` for short- or medium-duration purposes. I might check the file into the SCM system with `@pending` or `x:pending`, and that markup keeps CI systems running smoothly even when the test code or target code is still evolving.

Often, `@focus` has a greater immediacy than `@pending` or `<x:pending>` because `@focus` is how I say, "**Right now**, this is what I am working on and what I want the software to do to support my task." Sometimes, the immediacy is more important the positions of focus and pending within the tree structure of the XSpec file.

## Ease of explaining behavior

I think both behaviors are pretty easy to explain and understand conceptually. The current behavior is a drop simpler to explain, although ancestor-or-self precedence might be what a user assumes to be true before reading documentation.

**Current**: Focus takes precedence over pending.

**Potential change**: The nearest ancestor-or-self takes precedence. If an element has both `@pending` and `@focus`, then ... (whatever the decision is).

## Ease for users to achieve behavior that's unlike what's implemented

No matter which behavior XSpec implements related to pending vs. focus, you might occasionally want a different behavior. If one design makes that easier, that could be an advantage.

Under the current behavior, if you want a nearest-ancestor pending to override a more distant focus, you might find yourself commenting out scenarios or other test code, changing scenario hierarchy, or just not using the focus feature in that circumstance.

If the nearest ancestor-or-self takes precedence but you want a more distant focus to take effect, you might find yourself commenting out pending markup.

## Frequency with which the design choice matters

Infrequent, maybe. How often does it happen that all of the following are true?

* You're using `@focus` on a scenario
* The focused scenario contains something marked pending
* It's important that the pending code *not* execute, such as when it errors out and prevents the rest of the test from running. If the pending code fails but doesn't error out, that's less important for the short-term workflow that uses `@focus`.

## Where does it even matter whether focus or the nearest ancestor-or-self wins?
The design choice matters where a focused scenario contains code that is pending. For example:
```
<x:scenario focus="working on this now" label="Tests for foo">
  <x:pending label="this one errors out">
    <x:scenario label="case 1">...</x:scenario>
  </pending>
  <x:scenario label="case 2">...</x:scenario>
</x:scenario>
```
Why would that structure occur? I can think of a few cases that vary in ways related to the error in case 1.

### Check if old error has gone away
Case 1 was previously marked pending. You've changed the implementation of `foo` and now want to see if its tests still pass and if the previous error stops occurring. So, you add `@focus`.

You'd prefer that `@focus` take precedence so you can see if the previous error stops occurring.

If the nearest ancestor-or-self takes precedence, some things you can do instead: Remove or comment out the `x:pending` tags.

### Newly discovered error
To start, nothing is pending. Preparing to work on `foo` and its tests, you add `@focus`. Then you discover that case 1 errors out, preventing case 2 from running. So, you add `<x:pending>`.

You'd prefer that the nearest ancestor-or-self take precedence so you can see how case 2 behaves.

If `@focus` takes precedence, some things you can do instead: put case 2 on hold until you address the error in case 1; or, comment out the case 1 scenario instead of relying on `<x:pending>`; or, not use the focus feature here.

### Already know old error still occurs
Case 1 was previously marked pending and you know it will still error out (e.g., feature X of `foo` is incomplete). You've changed the implementation of `foo` and now want to see if its tests other than case 1 still pass. So, you add `@focus`.

You'd prefer that the nearest ancestor-or-self take precedence so you can work on case 2 without interference from case 1.

If `@focus` takes precedence, some things you can do instead: comment out the case 1 scenario instead of relying on `<x:pending>`; or, change the hierarchy (e.g., move the scenarios relying on feature X out from under "Tests for foo") at least until the error is resolved; or, not use the focus feature here.


## Existing tests related to interactions of pending and focus

* `test/pending-variable-inherited-by-focus.xspec`: Focused scenario inherits a variable defined outside, in pending ancestor

* `test/external_pending-scenario-param-inherited-by-focus.xspec`: Focused scenario inherits a scenario-level parameter defined outside, in pending ancestor

* `test/pending-shared-variable-inherited-by-focus.xspec`: Focused scenario inherits a variable defined in a shared scenario and referenced outside the focused scenario, in pending ancestor

* `test/external_pending-scenario-shared-param-inherited-by-focus.xspec`: Focused scenario inherits a scenario-level parameter defined in a shared scenario and referenced outside, in pending ancestor

* `test/end-to-end/cases/focus-vs-pending-attribute.xspec`: Sibling scenario of focused scenario does not run. Entire focused scenario runs, even the descendants marked pending.

* `test/end-to-end/cases/focus-vs-pending-element.xspec`: Same as above, except `x:pending/x:scenario` instead of `x:scenario[@pending]`

* `test/end-to-end/cases/focus-vs-pending.xspec`: Focus takes precedence over pending, whether pending markup occurs on an ancestor, a child, or the same element as focus.

* `test/end-to-end/cases/focus-vs-pending_schematron.xspec`: Focus takes precedence over pending when pending attribute occurs on a child of the scenario with focus.

## Potential new test cases

* Focused scenario inherits attribute-based behaviors (e.g., `@expand-text="yes"` or `catch="yes"`) from a pending ancestor.
* On a scenario with `shared="yes"`, `@pending` and `@focus` have no effect.
* If a scenario has `@pending` but not `shared="yes"`, it still runs if referenced via `<x:like>`. The mental model is that `<x:like>` looks at labels and ignores other attributes of the matching scenario.
* If a scenario has `@focus` but not `shared="yes"`, it does not run where referenced via `<x:like>` in an unfocused scenario.

**Comment by galtm** [comment]
> * [x]  Define the expected behavior
> * [x]  Fix the behavior (if necessary)

I think we should stick with the current "Focus takes precedence over pending" behavior as described in https://github.com/xspec/xspec/issues/575#issuecomment-1837518117.

**Comment by galtm** [comment]
> [x] Update Wiki

On https://github.com/xspec/xspec/wiki/Focusing-Your-Efforts, indicated that focus takes precedence over pending.

**Comment by galtm** [comment]
> * [x] Test the behavior, whatever the current behavior is

Augmented existing tests with #1999

**Comment by galtm** [comment]
> * [x] Consider creating Schematron rules for detecting meaningless `x:pending`, `@pending` or `@focus`

Added some Schematron rules with #2000.
