### ISSUE TITLE
Hints on test result report HTML

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#685]
https://github.com/xspec/xspec/pull/662#pullrequestreview-301002574

**Comment by AirQuick** [comment]
Added a Wiki [page](https://github.com/xspec/xspec/wiki/Understanding-Test-Results) as a starting point. (Incomplete. Not added to the sidebar yet.)

**Comment by AirQuick** [comment]
I've filled in the missing parts of the Wiki [page](https://github.com/xspec/xspec/wiki/Understanding-Test-Results) including https://github.com/xspec/xspec/pull/662#pullrequestreview-301002574. @galtm, please feel free to edit it further directly in Wiki or improve any linguistic/technical points.

And I added **Understanding Test Results** to the Wiki sidebar.

**Comment by galtm** [comment]
@AirQuick , the wiki page is really good. Thanks for clarifying so many things there! I made just a few minor edits directly in the wiki.

I changed "dim" to "grey" because naming the color seemed more direct. The page refers to colors by name in other spots. If you had a good reason for not saying grey here, it's OK to change it back to dim.

**Comment by AirQuick** [comment]
Thanks @galtm for polishing it.
There was no reason for selecting "dim". Indeed "grey" looks better.
