### ISSUE TITLE
x:label element accepts non-text nodes

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#801]
[`<x:label>`](https://github.com/xspec/xspec/blob/c0c1c224dbaac47718260c15ebc8534293d18e00/src/schemas/xspec.rnc#L98) accepts non-text nodes. But its reason is not known. The commit 148a65fcef7489fccfa29c3340ff812022798436 where `x:label` was introduced does not tell the reason.

Considering the commit replaces some `xsl:value-of` with `xsl:sequence`, it might have possibly wanted to report
```xml
<x:label xmlns="http://www.w3.org/1999/xhtml"><i>This</i> is a <b>label</b></x:label>
```
as
```html
<h2><i>This</i> is a <b>label</b></h2>
```
in the result HTML. But it didn't happen, because `mode="s:html-report"` in `format-xspec-report.xsl` does not handle `s:label`.

**Comment by AirQuick** [comment]
* `x:label` is not popular. I would say it's neglected. I haven't seen anyone (except me 😀) using it. The fact that `x:label` had been buggy for a long time (#308, #438) supports it.
* Labels are used at compile time for resolving `x:like`. So in general its structure should be simple.

Considering those points, I think we should replace this schema line
https://github.com/xspec/xspec/blob/349d614dea0eaf27c9c204315ac6f44242882283/src/schemas/xspec.rnc#L98
with
```
	element label { text }
```
to simplify it, until someone comes up with a cool idea to play with structured labels.

(Another question is why `label` in the schema lacks `common-attributes`. But I ignore it for now.)

@galtm
What do you think?

**Comment by galtm** [comment]
@AirQuick 
As another data point, my group doesn't use `x:label`, either. I don't see `x:label` mentioned in the two "getting started" wiki pages or the two "writing scenarios" wiki pages (each topic has one page covering Schematron and one covering XQuery/XSLT). Maybe that's why `x:label` is not popular.

I think it is fine to stop supporting structured labels and make the schema change you mentioned.

Just in case you change your mind and want to reduce the scope of the incompatibility, an alternative to the RelaxNG change could be to add a Schematron error for child elements in `x:label` elements that are used for resolving `x:like`. (However, if the XSpec document uses `x:import`, Schematron won't know which `x:label` elements are used for resolving `x:like` across files, right? In that case, the restriction on the content of `x:label` would go unenforced and would need to be documented some way other than Schematron.)

**Comment by AirQuick** [comment]
Thanks @galtm for the valuable input.
Schematron did not come to my mind. Thanks for reminding me of it.
Though Schematron would generally be a good solution, I think we can be bold to ignore compatibility in this particular case of `x:label`. I opened #820.

**Comment by galtm** [comment]
> we can be bold to ignore compatibility in this particular case

Sure, no problem.
